@startuml budget-lens
entity User {
  * user_id : UUID [PK]
  * username : VARCHAR
  * password_hash : VARCHAR
}

entity Expense {
  * expense_id : UUID [PK]
  * user_id : UUID [FK]
  * receipt_image : VARCHAR
  * category : VARCHAR
  * expense_date : DATE
  * amount : DECIMAL(10,2)
  * currency : VARCHAR
}

User ||--o{ Expense : has
@enduml